## Rows or Columns?

In [1]:
import numpy as np

In [3]:
X = np.ones((3,4))

In [4]:
X.shape

(3, 4)

In [5]:
X[0]

array([1., 1., 1., 1.])

In [8]:
for i,j in ((l,k) for l in range(X.shape[0]) for k in range(X.shape[1])):
    X[i,j] = i*10+j
X

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.],
       [20., 21., 22., 23.]])

In [9]:
O = np.zeros((3,4))

In [15]:
(np.arange(O.shape[0]).reshape(O.shape[0],1)*10 + 
 np.arange(O.shape[1]).reshape(1,O.shape[1]))

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [20]:
np.zeros((5,2,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [23]:
np.arange(5).reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [27]:
q = np.linalg.qr(np.random.normal(size=(5,5)))[0]

In [33]:
q.dot(q.transpose())

array([[ 1.00000000e+00, -7.75658640e-17,  2.14552226e-17,
         1.88646526e-16, -7.43500575e-17],
       [-7.75658640e-17,  1.00000000e+00,  1.43895579e-16,
         2.42170957e-16,  2.68603987e-16],
       [ 2.14552226e-17,  1.43895579e-16,  1.00000000e+00,
        -2.69501896e-16, -2.22235487e-16],
       [ 1.88646526e-16,  2.42170957e-16, -2.69501896e-16,
         1.00000000e+00, -1.86338665e-17],
       [-7.43500575e-17,  2.68603987e-16, -2.22235487e-16,
        -1.86338665e-17,  1.00000000e+00]])

In [68]:
Y = np.arange(1,6)[np.newaxis,:] + np.arange(1,4)[:,np.newaxis]*10
np.arange(1,6)[np.newaxis,:],np.arange(1,4)[:,np.newaxis]*10,Y

(array([[1, 2, 3, 4, 5]]),
 array([[10],
        [20],
        [30]]),
 array([[11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25],
        [31, 32, 33, 34, 35]]))

In [65]:
Y[0]

array([11, 21, 31, 41, 51])